version: "3"

services:

  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - DB:/var/lib/mysql
    networks:
      - netback
    ports:
      - 3306
    restart: on-failure

  wordpress:
    container_name: wordpress
    image: wordpress
    build:
      context: ./requirements/wordpress
    env_file:
      - .env


    env_file:
      - .env
    volumes:
      - WordPress:/var/www/html
    networks:
      - netback
    ports:
      - 9000
      - 3306
    restart: on-failure
    depends_on:
      - mariadb

  nginx:
    container_name: nginx
    image: nginx
    build:
      context: ./requirements/nginx
    volumes:
      - WordPress:/var/www/html
    env_file:
      - .env
    networks:
      - netback
    ports:
      - 443:443
      - 9000
    restart: on-failure
    depends_on:
      - wordpress

volumes:

  DB:
    driver: local
    driver_opts:
      type: none
      device: /home/$USER/data/DB
      o: bind

  WordPress:
    driver: local
    driver_opts:
      type: none
      device: /home/$USER/data/WordPress
      o: bind

networks:

  netback:
    driver: bridge