version: '3'
services:
  nginx:
    # image: nginx:latest
    build: ./srcs/requirements/nginx
    volumes:
      - wp:/var/www/wordpress
    restart: always
    env_file: .env
    ports:
      - "5656:443"
    networks:
      - netback

  mariadb:
    build: ./srcs/requirements/mariadb
    restart: always
    env_file: .env
    volumes:
      - db:/var/lib/mysql
    networks:
      - netback

  # wordpress:
  #   build: ./srcs/requirements/wordpress

# volumes:
#   wp:
#     driver: local
#     name: wp
#     driver_opts:
#       type: none
#       o: bind
#       device: ~/data/wordpress #TODO: passer sur home/data pour la VM

#   db:
#     driver: local
#     name: db
#     driver_opts:
#       type: none
#       o: bind
#       device: ~/data/mariadb #TODO: passer sur home/data pour la VM

volumes:
  wp:
    driver: local
  db:
    driver: local

networks:
  netback:
    name: netback
    driver: bridge

    # environment:
    #   MYSQL_ROOT_PASSWORD: somewordpress
    #   MYSQL_DATABASE: wordpress
    #   MYSQL_USER: wordpress
    #   MYSQL_PASSWORD: wordpress
    





  # mariadb:
  #   container_name: mariadb
  #   build: ./requirements/mariadb
  #   env_file:
  #     - .env
  #   volumes:
  #     - db:/var/lib/mysql
  #   networks:
  #     - app-network
  #   restart: always

  # wordpress:
  #   container_name: wordpress
  #   build: ./requirements/wordpress
  #   env_file:
  #     - .env
  #   depends_on:
  #     - mariadb
  #   volumes:
  #     - wp:/var/www/html
  #   networks:
  #     - app-network
  #   restart: always

  # nginx:
  #   container_name: nginx
  #   build: ./requirements/nginx
  #   ports:
  #     - "443:443"
  #   # depends_on:
  #   #   - wordpress
  #   # volumes:
  #   #   - wp:/var/www/html
  #   # networks:
  #   #   - app-network
  #   restart: always