CREATE DATABASE IF NOT EXISTS ${WORDPRESS_DB_NAME}; \
CREATE USER ${WORDPRESS_DB_USER}@'%' IDENTIFIED BY ${WORDPRESS_DB_PASSWORD}; \
GRANT ALL ON *.* TO ${WORDPRESS_DB_USER}@'%'; \
FLUSH PRIVILEGES; \
ALTER USER 'root'@'localhost' IDENTIFIED BY ${MARIADB_ROOT_PASSWD};
